"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import MediaUrlEditor from "./media-url-editor";

type Product={ id?:number;name:string;category:string;series:string;brand:string;model:string;year:string;sku:string;barcode:string;description:string;accent:string;imageUrl?:string|null;imageUrls:string[];videoUrls:string[];defaultImageUrl?:string|null };
type Category={ id:number;name:string;productCount:number;defaultImageUrl:string };
type Brand={ id:number;name:string;productCount:number };
type AdminUser={ id:number;username:string;createdAt?:string;updatedAt?:string };
type ExcelInfo={ fileName:string|null;size:number;updatedAt:string|null;version:number };
const blankProduct=():Product=>({ name:"",category:"手機底座",series:"底座款",brand:"",model:"",year:"",sku:"",barcode:"",description:"",accent:"#f97316",imageUrl:null,imageUrls:[],videoUrls:[] });

export default function AdminPage(){
  const [products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[brands,setBrands]=useState<Brand[]>([]),[users,setUsers]=useState<AdminUser[]>([]);
  const [currentUser,setCurrentUser]=useState<AdminUser|null>(null),[setupRequired,setSetupRequired]=useState(false),[authLoading,setAuthLoading]=useState(true);
  const [authUsername,setAuthUsername]=useState(""),[authPassword,setAuthPassword]=useState(""),[authConfirm,setAuthConfirm]=useState(""),[authError,setAuthError]=useState("");
  const [draft,setDraft]=useState<Product>(blankProduct),[query,setQuery]=useState(""),[category,setCategory]=useState("全部"),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[editorOpen,setEditorOpen]=useState(false);
  const [catalogName,setCatalogName]=useState(""),[excelInfo,setExcelInfo]=useState<ExcelInfo>({ fileName:null,size:0,updatedAt:null,version:1 }),[excelUploading,setExcelUploading]=useState(false);
  const [categoryDraft,setCategoryDraft]=useState(""),[editingCategoryId,setEditingCategoryId]=useState<number|null>(null),[brandDraft,setBrandDraft]=useState(""),[editingBrandId,setEditingBrandId]=useState<number|null>(null);
  const [categoryImageDrafts,setCategoryImageDrafts]=useState<Record<number,string>>({});
  const [accountDraft,setAccountDraft]=useState<{ id?:number;username:string;password:string }>({ username:"",password:"" });
  const [contactEmail,setContactEmail]=useState("sales@ianautostore.com");

  async function load(){
    const responses=await Promise.all([fetch("/api/products"),fetch("/api/categories"),fetch("/api/brands"),fetch("/api/excel"),fetch("/api/admin/users"),fetch("/api/settings")]);
    if(responses.some((response)=>response.status===401)){setCurrentUser(null);return;}
    const [productData,categoryData,brandData,excelData,userData,settingsData]=await Promise.all(responses.map((response)=>response.json()));
    if(responses[0].ok)setProducts(productData.products);if(responses[1].ok){setCategories(categoryData.categories);setCategoryImageDrafts(Object.fromEntries(categoryData.categories.map((item:Category)=>[item.id,item.defaultImageUrl||""])));}if(responses[2].ok)setBrands(brandData.brands);if(responses[3].ok)setExcelInfo(excelData);if(responses[4].ok)setUsers(userData.users);if(responses[5].ok)setContactEmail(settingsData.contactEmail);
  }
  useEffect(()=>{fetch("/api/auth/session").then((response)=>response.json()).then(async(data)=>{setSetupRequired(Boolean(data.setupRequired));setCurrentUser(data.authenticated?data.user:null);if(data.authenticated)await load();}).catch(()=>setAuthError("無法連線管理後台")).finally(()=>setAuthLoading(false));},[]);
  const visible=useMemo(()=>products.filter((item)=>(category==="全部"||item.category===category)&&[item.name,item.brand,item.model,item.sku].join(" ").toLowerCase().includes(query.toLowerCase())),[products,category,query]);

  async function submitAuth(event:FormEvent){event.preventDefault();setAuthError("");if(setupRequired&&authPassword!==authConfirm){setAuthError("兩次輸入的密碼不一致");return;}setSaving(true);try{const response=await fetch(setupRequired?"/api/auth/setup":"/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:authUsername,password:authPassword})});const data=await response.json();if(!response.ok)throw new Error(data.error||"登入失敗");setCurrentUser(data.user);setSetupRequired(false);setAuthPassword("");setAuthConfirm("");await load();}catch(error){setAuthError(error instanceof Error?error.message:"登入失敗");}finally{setSaving(false);}}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});setCurrentUser(null);setAuthPassword("");setMessage("");}
  function startNew(){setDraft({...blankProduct(),category:categories[0]?.name||"手機底座",brand:brands[0]?.name||""});setMessage("");setEditorOpen(true);}function edit(item:Product){setDraft({...item,imageUrls:item.imageUrls?.length?[...item.imageUrls]:item.imageUrl?[item.imageUrl]:[],videoUrls:[...(item.videoUrls||[])]});setMessage("");setEditorOpen(true);}
  async function upload(file:File,kind="image"){const form=new FormData();form.append("file",file);form.append("kind",kind);const response=await fetch("/api/uploads",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||"上傳失敗");return data;}
  async function uploadProductImages(files:FileList){setSaving(true);setMessage("");try{const urls:string[]=[];for(const file of Array.from(files)){const data=await upload(file);urls.push(String(data.url));}setDraft((current)=>({...current,imageUrls:[...current.imageUrls,...urls]}));setMessage(`${urls.length} 張商品圖片已上傳，請記得儲存商品`);}catch(error){setMessage(error instanceof Error?error.message:"圖片上傳失敗");}finally{setSaving(false);}}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setMessage("");try{const payload={...draft,imageUrls:draft.imageUrls.map((url)=>url.trim()).filter(Boolean),videoUrls:draft.videoUrls.map((url)=>url.trim()).filter(Boolean)};const response=await fetch(draft.id?`/api/products/${draft.id}`:"/api/products",{method:draft.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error);await load();setEditorOpen(false);setDraft(blankProduct());setMessage(draft.id?"商品已更新":"商品已新增");}catch(error){setMessage(error instanceof Error?error.message:"儲存失敗");}finally{setSaving(false);}}
  async function remove(item:Product){if(!item.id||!confirm(`確定刪除「${item.name}」？`))return;const response=await fetch(`/api/products/${item.id}`,{method:"DELETE"});const data=await response.json();if(!response.ok){setMessage(data.error||"刪除失敗");return;}await load();setMessage("商品已刪除");}

  async function saveCategory(id?:number,nameOverride?:string){const name=(nameOverride??categoryDraft).trim();if(!name){setMessage("請輸入商品分類名稱");return;}setSaving(true);setMessage("");try{const response=await fetch(id?`/api/categories/${id}`:"/api/categories",{method:id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name})});const data=await response.json();if(!response.ok)throw new Error(data.error);setCategoryDraft("");setEditingCategoryId(null);await load();setMessage(id?"商品分類已更新，相關商品已同步":"商品分類已新增");}catch(error){setMessage(error instanceof Error?error.message:"分類儲存失敗");}finally{setSaving(false);}}
  async function deleteCategory(item:Category){if(!confirm(`確定刪除「${item.name}」分類？`))return;const response=await fetch(`/api/categories/${item.id}`,{method:"DELETE"});const data=await response.json();if(!response.ok){setMessage(data.error||"無法刪除分類");return;}await load();setMessage("商品分類已刪除");}
  async function saveCategoryImage(item:Category,urlOverride?:string){const defaultImageUrl=(urlOverride??categoryImageDrafts[item.id]??"").trim();setSaving(true);setMessage("");try{const response=await fetch(`/api/categories/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({defaultImageUrl})});const data=await response.json();if(!response.ok)throw new Error(data.error);await load();setMessage(defaultImageUrl?`「${item.name}」預設圖片已更新`:`「${item.name}」預設圖片已清除`);}catch(error){setMessage(error instanceof Error?error.message:"預設圖片儲存失敗");}finally{setSaving(false);}}
  async function uploadCategoryImage(item:Category,file:File){setSaving(true);setMessage("");try{const data=await upload(file,"category-default");setCategoryImageDrafts((current)=>({...current,[item.id]:data.url}));await saveCategoryImage(item,data.url);}catch(error){setMessage(error instanceof Error?error.message:"預設圖片上傳失敗");setSaving(false);}}
  async function saveBrand(id?:number,nameOverride?:string){const name=(nameOverride??brandDraft).trim();if(!name){setMessage("請輸入品牌名稱");return;}setSaving(true);setMessage("");try{const response=await fetch(id?`/api/brands/${id}`:"/api/brands",{method:id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name})});const data=await response.json();if(!response.ok)throw new Error(data.error);setBrandDraft("");setEditingBrandId(null);await load();setMessage(id?"品牌已更新，相關商品已同步":"品牌已新增");}catch(error){setMessage(error instanceof Error?error.message:"品牌儲存失敗");}finally{setSaving(false);}}
  async function deleteBrand(item:Brand){if(!confirm(`確定刪除「${item.name}」品牌？`))return;const response=await fetch(`/api/brands/${item.id}`,{method:"DELETE"});const data=await response.json();if(!response.ok){setMessage(data.error||"無法刪除品牌");return;}await load();setMessage("品牌已刪除");}
  async function saveAccount(){if(!accountDraft.username.trim()){setMessage("請輸入帳號");return;}if(!accountDraft.id&&accountDraft.password.length<8){setMessage("新帳號密碼至少需要 8 個字元");return;}setSaving(true);setMessage("");try{const response=await fetch(accountDraft.id?`/api/admin/users/${accountDraft.id}`:"/api/admin/users",{method:accountDraft.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(accountDraft)});const data=await response.json();if(!response.ok)throw new Error(data.error);setAccountDraft({username:"",password:""});if(data.forceLogout){setCurrentUser(null);return;}await load();setMessage(accountDraft.id?"管理員帳號已更新":"管理員帳號已新增");}catch(error){setMessage(error instanceof Error?error.message:"帳號儲存失敗");}finally{setSaving(false);}}
  async function deleteAccount(item:AdminUser){if(!confirm(`確定刪除管理員帳號「${item.username}」？`))return;const response=await fetch(`/api/admin/users/${item.id}`,{method:"DELETE"});const data=await response.json();if(!response.ok){setMessage(data.error||"無法刪除帳號");return;}await load();setMessage("管理員帳號已刪除");}
  async function importExcel(file:File){if(!confirm(`上傳「${file.name}」會整批取代目前所有商品資料，確定繼續？`))return;setExcelUploading(true);setMessage("");try{const form=new FormData();form.append("file",file);const response=await fetch("/api/excel",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error);await load();setMessage(`Excel V${data.version} 更新完成：共 ${data.productCount} 筆商品、${data.imageCount} 張內嵌圖片`);}catch(error){setMessage(error instanceof Error?error.message:"Excel 匯入失敗");}finally{setExcelUploading(false);}}
  async function saveContactEmail(){setSaving(true);setMessage("");try{const response=await fetch("/api/settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({contactEmail})});const data=await response.json();if(!response.ok)throw new Error(data.error);setContactEmail(data.contactEmail);setMessage("聯絡 Email 已更新，前台按鈕已同步");}catch(error){setMessage(error instanceof Error?error.message:"Email 儲存失敗");}finally{setSaving(false);}}

  if(authLoading)return <main className="admin-auth-shell"><div className="auth-loading"><span className="detail-loader"/><p>正在開啟管理後台…</p></div></main>;
  if(!currentUser)return <main className="admin-auth-shell"><section className="admin-auth-card"><Link className="auth-brand" href="/"><span className="brand-wordmark"><b>閎麗國際有限公司</b><small>SECURE ADMIN</small></span></Link><div className="auth-copy"><p>{setupRequired?"FIRST-TIME SETUP":"ADMIN SIGN IN"}</p><h1>{setupRequired?"建立第一個管理員":"登入管理後台"}</h1><span>{setupRequired?"設定完成後，往後將使用此帳號與密碼登入。":"請輸入管理員帳號與密碼以繼續。"}</span></div><form className="auth-form" onSubmit={submitAuth}><label>管理員帳號<input autoComplete="username" required value={authUsername} onChange={(event)=>setAuthUsername(event.target.value)} placeholder="至少 3 個英數字元"/></label><label>密碼<input type="password" autoComplete={setupRequired?"new-password":"current-password"} required minLength={8} value={authPassword} onChange={(event)=>setAuthPassword(event.target.value)} placeholder="至少 8 個字元"/></label>{setupRequired&&<label>再次輸入密碼<input type="password" autoComplete="new-password" required minLength={8} value={authConfirm} onChange={(event)=>setAuthConfirm(event.target.value)}/></label>}{authError&&<p className="auth-error">{authError}</p>}<button className="admin-primary" disabled={saving}>{saving?"處理中…":setupRequired?"建立管理員並進入後台":"登入後台"}</button></form><Link className="auth-home-link" href="/">← 返回 閎麗國際有限公司</Link></section></main>;

  return <main className="admin-shell"><aside className="admin-sidebar"><Link className="brand" href="/"><span className="brand-wordmark"><b>閎麗國際有限公司</b><small>ADMIN CENTER</small></span></Link><nav><a className="active" href="#products"><span>▦</span>商品管理</a><a href="#product-media"><span>▶</span>圖片與影片</a><a href="#excel-sync"><span>⇄</span>Excel 更新</a><a href="#categories"><span>◫</span>商品分類</a><a href="#category-images"><span>▣</span>分類預設圖片</a><a href="#brands"><span>◇</span>汽車品牌</a><a href="#accounts"><span>♙</span>管理員帳號</a><a href="#catalog-pdf"><span>▤</span>品項總覽 PDF</a><a href="#contact-settings"><span>＠</span>聯絡 Email</a><Link href="/" target="_blank"><span>↗</span>查看前台網站</Link></nav><button className="sidebar-logout" onClick={logout}>登出 {currentUser.username}</button></aside><section className="admin-main"><header className="admin-topbar"><div><p>管理後台 / PRODUCT CMS</p><h1>商品管理</h1></div><Link href="/">返回網站 ↗</Link></header>{message&&<div className="admin-toast">{message}<button onClick={()=>setMessage("")}>×</button></div>}<div className="admin-summary"><article><span>商品總數</span><strong>{products.length}</strong><small>個有效品項</small></article><article><span>汽車廠牌</span><strong>{brands.length}</strong><small>個適用品牌</small></article><article><span>產品分類</span><strong>{categories.length}</strong><small>個可用品類</small></article></div>

    <details className="admin-panel excel-panel collapsible-panel" id="excel-sync" open><summary className="panel-title"><div><p className="panel-kicker">EXCEL DATA SYNC</p><h2>Excel 商品資料更新</h2></div><div className="summary-meta"><span className="version-badge">CURRENT V{excelInfo.version}</span><span className="collapse-indicator" aria-hidden="true">⌄</span></div></summary><div className="excel-version-card"><span className="excel-icon">XLSX</span><div className="excel-file-info"><small>目前最新版本</small><b>{excelInfo.fileName||"尚未上傳 Excel"}</b><span>{excelInfo.updatedAt?`更新於 ${new Date(excelInfo.updatedAt).toLocaleString("zh-TW")}`:"等待第一次上傳"}・{products.length} 筆商品</span></div><div className="excel-actions"><a className="admin-secondary" href="/api/excel/export">匯出目前 Excel</a><label className="admin-primary upload-pill"><input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(event)=>{const file=event.target.files?.[0];if(file)void importExcel(file);event.currentTarget.value="";}}/>{excelUploading?"更新中…":"上傳新版 Excel"}</label></div></div></details>

    <ManagePanel kind="category" title="商品分類管理" kicker="CATEGORY SETTINGS" id="categories" draft={categoryDraft} setDraft={setCategoryDraft} editingId={editingCategoryId} setEditingId={setEditingCategoryId} items={categories} saving={saving} onSave={saveCategory} onDelete={deleteCategory}/>
    <CategoryImagePanel items={categories} drafts={categoryImageDrafts} setDrafts={setCategoryImageDrafts} saving={saving} onSave={saveCategoryImage} onUpload={uploadCategoryImage}/>
    <ManagePanel kind="brand" title="汽車品牌管理" kicker="BRAND SETTINGS" id="brands" draft={brandDraft} setDraft={setBrandDraft} editingId={editingBrandId} setEditingId={setEditingBrandId} items={brands} saving={saving} onSave={saveBrand} onDelete={deleteBrand}/>

    <details className="admin-panel collapsible-panel" id="products" open><summary className="panel-title"><div><h2>所有商品</h2></div><span className="collapse-indicator" aria-hidden="true">⌄</span></summary><div className="panel-body-actions"><button type="button" className="admin-primary" onClick={startNew}>＋ 新增商品</button></div><div className="admin-filters"><label className="admin-search">⌕<input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="搜尋品名、廠牌、型號或 SKU"/></label><select value={category} onChange={(event)=>setCategory(event.target.value)}><option>全部</option>{categories.map((item)=><option key={item.id}>{item.name}</option>)}</select></div><div className="product-table-wrap"><table className="product-table"><thead><tr><th>商品</th><th>車型階級</th><th>分類</th><th>廠商報價 SKU</th><th>操作</th></tr></thead><tbody>{visible.map((item)=>{const resolvedImage=item.imageUrls?.[0]||item.imageUrl||item.defaultImageUrl;return <tr key={item.id}><td><div className="table-product">{resolvedImage?<img src={resolvedImage} alt=""/>:<span>{item.category.slice(0,1)}</span>}<div><b>{item.name}</b><small>{item.barcode?`EAN ${item.barcode}`:"未提供國際條碼"}</small></div></div></td><td><b>{item.brand} / {item.model}</b><small>{item.year}</small></td><td><em>{item.category}・{item.series}</em></td><td><code>{item.sku}</code></td><td><div className="table-actions"><button onClick={()=>edit(item)}>編輯</button><button className="danger" onClick={()=>void remove(item)}>刪除</button></div></td></tr>;})}</tbody></table>{!visible.length&&<div className="table-empty">找不到符合條件的商品</div>}</div></details>

    <details className="admin-panel collapsible-panel" id="product-media" open><summary className="panel-title"><div><p className="panel-kicker">PRODUCT MEDIA</p><h2>商品圖片與影片</h2></div><span className="collapse-indicator" aria-hidden="true">⌄</span></summary><div className="product-media-admin-grid">{products.map((item)=>{const image=item.imageUrls?.[0]||item.imageUrl||item.defaultImageUrl;return <article key={item.id}>{image?<img src={image} alt=""/>:<span className="product-media-placeholder">{item.category.slice(0,2)}</span>}<div><b>{item.name}</b><small>{item.imageUrls?.length||0} 張圖片・{item.videoUrls?.length||0} 支影片</small></div><button type="button" onClick={()=>edit(item)}>管理媒體</button></article>;})}</div></details>

    <details className="admin-panel account-panel collapsible-panel" id="accounts" open><summary className="panel-title"><div><p className="panel-kicker">ADMIN ACCOUNTS</p><h2>管理員帳號與密碼</h2></div><span className="collapse-indicator" aria-hidden="true">⌄</span></summary><div className="account-manager"><form className="account-form" onSubmit={(event)=>{event.preventDefault();void saveAccount();}}><label>帳號<input value={accountDraft.username} onChange={(event)=>setAccountDraft({...accountDraft,username:event.target.value})} placeholder="英文帳號"/></label><label>{accountDraft.id?"新密碼（留空則不變）":"密碼"}<input type="password" value={accountDraft.password} onChange={(event)=>setAccountDraft({...accountDraft,password:event.target.value})} placeholder="至少 8 個字元"/></label><button type="submit" className="admin-primary" disabled={saving}>{accountDraft.id?"儲存帳號":"＋ 新增帳號"}</button>{accountDraft.id&&<button type="button" className="admin-text-button" onClick={()=>setAccountDraft({username:"",password:""})}>取消</button>}</form><div className="account-list">{users.map((item)=><article key={item.id}><div><b>{item.username}</b><small>{item.id===currentUser.id?"目前登入帳號":"管理員"}</small></div><div><button onClick={()=>setAccountDraft({id:item.id,username:item.username,password:""})}>編輯</button><button className="danger" disabled={item.id===currentUser.id} onClick={()=>void deleteAccount(item)}>刪除</button></div></article>)}</div></div></details>

    <details className="admin-panel pdf-panel collapsible-panel" id="catalog-pdf" open><summary className="panel-title"><div><p className="panel-kicker">CATALOG FILE</p><h2>品項總覽 PDF</h2></div><span className="collapse-indicator" aria-hidden="true">⌄</span></summary><div className="pdf-panel-body"><span className="pdf-icon">PDF</span><div className="pdf-file-copy"><b>{catalogName||"目前尚未顯示檔案名稱"}</b></div><label className="upload-button"><input type="file" accept="application/pdf" onChange={async(event)=>{const file=event.target.files?.[0];if(!file)return;try{setSaving(true);const data=await upload(file,"catalog");setCatalogName(data.name);setMessage("品項總覽 PDF 已更新");}catch(error){setMessage(error instanceof Error?error.message:"上傳失敗");}finally{setSaving(false);}}}/>{saving?"上傳中…":"上傳 PDF"}</label></div></details>

    <details className="admin-panel contact-settings-panel collapsible-panel" id="contact-settings" open><summary className="panel-title"><div><p className="panel-kicker">CONTACT SETTINGS</p><h2>聯絡業務 Email</h2></div><span className="collapse-indicator" aria-hidden="true">⌄</span></summary><form className="contact-settings-form" onSubmit={(event)=>{event.preventDefault();void saveContactEmail();}}><label>Email<input type="email" required value={contactEmail} onChange={(event)=>setContactEmail(event.target.value)} placeholder="sales@ianautostore.com"/></label><button type="submit" className="admin-primary" disabled={saving}>{saving?"儲存中…":"儲存 Email"}</button></form></details>
  </section>{editorOpen&&<div className="editor-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)setEditorOpen(false);}}>
    <form className="product-editor" onSubmit={submit}>
      <div className="editor-header"><div><p>{draft.id?`PRODUCT #${draft.id}`:"NEW PRODUCT"}</p><h2>{draft.id?"編輯商品":"新增商品"}</h2></div><button type="button" onClick={()=>setEditorOpen(false)}>×</button></div>
      <div className="editor-scroll">
        <fieldset><legend>01 / 必填資料</legend><div className="editor-grid three"><label>汽車廠牌<select required value={draft.brand} onChange={(event)=>setDraft({...draft,brand:event.target.value})}><option value="">選擇品牌</option>{brands.map((item)=><option key={item.id}>{item.name}</option>)}</select></label><label>車款型號<input required value={draft.model} onChange={(event)=>setDraft({...draft,model:event.target.value})} placeholder="例如 Corolla Cross"/></label><label>商品分類<select required value={draft.category} onChange={(event)=>setDraft({...draft,category:event.target.value})}>{categories.map((item)=><option key={item.id}>{item.name}</option>)}</select></label></div></fieldset>
        <fieldset><legend>02 / 選填資料</legend><div className="editor-grid two"><label>商品名稱<input value={draft.name} onChange={(event)=>setDraft({...draft,name:event.target.value})} placeholder="空白時由系統產生"/></label><label>適用年份<input value={draft.year} onChange={(event)=>setDraft({...draft,year:event.target.value})} placeholder="空白時顯示未指定"/></label><label>商品系列<input value={draft.series} onChange={(event)=>setDraft({...draft,series:event.target.value})} placeholder="空白時使用標準版"/></label><label>廠商報價 SKU<input value={draft.sku} onChange={(event)=>setDraft({...draft,sku:event.target.value})} placeholder="空白時顯示未提供"/></label><label>國際條碼 EAN<input value={draft.barcode} onChange={(event)=>setDraft({...draft,barcode:event.target.value})}/></label></div><label className="full-label">商品說明<textarea rows={4} value={draft.description} onChange={(event)=>setDraft({...draft,description:event.target.value})} placeholder="空白時由系統依分類、品牌與車型產生"/></label></fieldset>
        <fieldset><legend>03 / 商品圖片</legend><MediaUrlEditor kind="image" urls={draft.imageUrls} onChange={(imageUrls)=>setDraft({...draft,imageUrls})} onUpload={(files)=>void uploadProductImages(files)}/></fieldset>
        <fieldset><legend>04 / 商品影片</legend><MediaUrlEditor kind="video" urls={draft.videoUrls} onChange={(videoUrls)=>setDraft({...draft,videoUrls})}/></fieldset>
      </div>
      <div className="editor-footer"><button type="button" onClick={()=>setEditorOpen(false)}>取消</button><button className="admin-primary" disabled={saving}>{saving?"儲存中…":draft.id?"儲存變更":"新增商品"}</button></div>
    </form>
  </div>}</main>;
}

function CategoryImagePanel({items,drafts,setDrafts,saving,onSave,onUpload}:{items:Category[];drafts:Record<number,string>;setDrafts:React.Dispatch<React.SetStateAction<Record<number,string>>>;saving:boolean;onSave:(item:Category,url?:string)=>Promise<void>;onUpload:(item:Category,file:File)=>Promise<void>}){
  return <details className="admin-panel category-image-panel collapsible-panel" id="category-images" open><summary className="panel-title"><div><p className="panel-kicker">CATEGORY DEFAULT IMAGES</p><h2>分類預設圖片</h2></div><span className="collapse-indicator" aria-hidden="true">⌄</span></summary><div className="category-image-grid">{items.map((item)=>{const url=drafts[item.id]??item.defaultImageUrl??"";return <article className="category-image-card" key={item.id}><div className="category-image-preview">{url?<img src={url} alt={`${item.name}預設圖片`}/>:<span>{item.name.slice(0,2)}</span>}</div><div className="category-image-fields"><b>{item.name}</b><label>圖片網址<input type="url" value={url} onChange={(event)=>setDrafts((current)=>({...current,[item.id]:event.target.value}))} placeholder="https://.../image.jpg"/></label><div className="category-image-actions"><label className="admin-secondary upload-pill"><input type="file" accept="image/*" onChange={(event)=>{const file=event.target.files?.[0];if(file)void onUpload(item,file);event.currentTarget.value="";}}/>上傳圖片</label><button type="button" className="admin-primary" disabled={saving} onClick={()=>void onSave(item)}>儲存</button><button type="button" className="admin-text-button" disabled={saving||!url} onClick={()=>{setDrafts((current)=>({...current,[item.id]:""}));void onSave(item,"");}}>清除</button></div></div></article>;})}</div></details>;
}

type ManageItem={id:number;name:string;productCount:number};
function ManagePanel({kind,title,kicker,id,draft,setDraft,editingId,setEditingId,items,saving,onSave,onDelete}:{kind:"category"|"brand";title:string;kicker:string;id:string;draft:string;setDraft:(value:string)=>void;editingId:number|null;setEditingId:(value:number|null)=>void;items:ManageItem[];saving:boolean;onSave:(id?:number,name?:string)=>Promise<void>;onDelete:(item:ManageItem)=>Promise<void>}){
  const noun=kind==="brand"?"品牌":"分類";
  return <details className="admin-panel category-panel collapsible-panel" id={id} open><summary className="panel-title"><div><p className="panel-kicker">{kicker}</p><h2>{title}</h2></div><span className="collapse-indicator" aria-hidden="true">⌄</span></summary><div className="category-manager"><form className="category-create" onSubmit={(event)=>{event.preventDefault();void onSave();}}><input value={editingId?"":draft} disabled={Boolean(editingId)} onChange={(event)=>setDraft(kind==="brand"?event.target.value.toUpperCase():event.target.value)} placeholder={editingId?"請先完成卡片內的編輯":`輸入${noun}名稱`}/><button type="submit" className="admin-primary" disabled={saving||Boolean(editingId)||!draft.trim()}>＋ 新增{noun}</button></form><div className="category-list">{items.map((item)=><article key={item.id}>{editingId===item.id?<><input className="inline-manage-input" autoFocus value={draft} onChange={(event)=>setDraft(kind==="brand"?event.target.value.toUpperCase():event.target.value)}/><div><button type="button" onClick={()=>void onSave(item.id,draft)}>儲存</button><button type="button" onClick={()=>{setEditingId(null);setDraft("");}}>取消</button></div></>:<><div><b>{item.name}</b><small>{item.productCount} 筆商品</small></div><div><button type="button" onClick={()=>{setEditingId(item.id);setDraft(item.name);}}>編輯</button><button type="button" className="danger" onClick={()=>void onDelete(item)}>刪除</button></div></>}</article>)}</div></div></details>;
}
